[package]
name = "email-type-rs"
version = "1.0.0"
edition = "2021"

[features]
default = []
utils = []

[dependencies]
thiserror = "1.0.31"

validate = "0.6.1"

serde = { version = "1.0", features = ["derive"] }

log = "0.4"

[dev-dependencies]
env_logger = "0.8"
fake = "2"